requires = ["tox>=4"]
env_list = ["testing"]

[env.testing]
description = "Run pytest and unittest"
deps = [
    "pytest>=8",
    "numpy>=1.15.0",
    "matplotlib>=3.0.0"
]
commands = [
    ["pytest"],
    ["python", "-m", "unittest", "discover", "-s", "tests/unit"]
]